### ISSUE TITLE
[Start up] When AIDE is started while AIDE VM is down, the application error message box pops up more than once and crashes.

### ISSUE THREAD

**Issue by charissasylim** [rsx-labs/aide-frontend#560]
**Describe the bug**
When AIDE is started while AIDE VM is down, the application error message box pops up more than once.

**Expected behavior**
Application error message should display once only.

**Version (please complete the following information):**
 - Version 3.3.2

**Comment by charissasylim** [comment]
Error message during startup -
2020-06-01 06:57:42.0793::INFO::UI_AIDE_CommCellServices.MainWindow::****** Starting AIDE 3.3.4 ******
2020-06-01 06:57:42.1514::DEBUG::UI_AIDE_CommCellServices.MainWindow::Start : Constructor
2020-06-01 06:57:42.1514::DEBUG::UI_AIDE_CommCellServices.MainWindow::Start : LoadOnce
2020-06-01 06:57:42.1565::DEBUG::UI_AIDE_CommCellServices.MainWindow::Checking for existing instance. Count = 0
2020-06-01 06:57:42.1565::DEBUG::UI_AIDE_CommCellServices.MainWindow::End : LoadOnce
2020-06-01 06:57:42.2497::DEBUG::UI_AIDE_CommCellServices.MainWindow::Start : InitializeService
2020-06-01 06:57:43.9803::INFO::UI_AIDE_CommCellServices.MainWindow::Opening AIDE service ...
2020-06-01 06:57:43.9803::DEBUG::UI_AIDE_CommCellServices.MainWindow::End : InitializeService
2020-06-01 06:57:43.9853::DEBUG::UI_AIDE_CommCellServices.MainWindow::Start : GetOptionData
2020-06-01 06:57:43.9853::DEBUG::UI_AIDE_CommCellServices.OptionViewModel::Start : Constructor
2020-06-01 06:57:43.9853::DEBUG::UI_AIDE_CommCellServices.OptionViewModel::End : Constructor
2020-06-01 06:57:43.9853::DEBUG::UI_AIDE_CommCellServices.OptionViewModel::Start : GetOptions 0
2020-06-01 06:58:13.0518::DEBUG::UI_AIDE_CommCellServices.OptionViewModel::Start : SetOptions
2020-06-01 06:58:13.0518::DEBUG::UI_AIDE_CommCellServices.OptionViewModel::End : SetOptions
2020-06-01 06:58:13.0518::DEBUG::UI_AIDE_CommCellServices.MainWindow::Start : CheckOutlook
2020-06-01 06:58:17.6572::DEBUG::UI_AIDE_CommCellServices.MainWindow::End : CheckOutlook
2020-06-01 06:58:17.6572::DEBUG::UI_AIDE_CommCellServices.MainWindow::Start : InitializeData
2020-06-01 06:58:17.6572::DEBUG::UI_AIDE_CommCellServices.MainWindow::Start : SetEmployeeData
2020-06-01 06:58:17.6733::DEBUG::UI_AIDE_CommCellServices.MainWindow::Start : SignOn
2020-06-01 06:58:17.7445::DEBUG::UI_AIDE_CommCellServices.MainWindow::End : SignOn result = False
2020-06-01 06:58:17.7445::DEBUG::UI_AIDE_CommCellServices.MainWindow::End : SetEmployeeData
2020-06-01 06:58:17.8119::DEBUG::UI_AIDE_CommCellServices.MainWindow::Start : Attendance
2020-06-01 06:58:18.2550::ERROR::UI_AIDE_CommCellServices.MainWindow::System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at UI_AIDE_CommCellServices.MainWindow.Attendance()
2020-06-01 08:10:24.2358::DEBUG::UI_AIDE_CommCellServices.MainWindow::End : Attendance
2020-06-01 08:10:24.2638::DEBUG::UI_AIDE_CommCellServices.MainWindow::Start : LoadSideBar
2020-06-01 08:10:24.2709::DEBUG::UI_AIDE_CommCellServices.AttendanceDashBoard::Start : Constructor
2020-06-01 08:10:24.3220::DEBUG::UI_AIDE_CommCellServices.AttendanceDashBoard::Start : SetData
2020-06-01 08:10:29.8792::ERROR::UI_AIDE_CommCellServices.AttendanceDashBoard::System.NullReferenceException: Object reference not set to an instance of an object.
   at UI_AIDE_CommCellServices.AttendanceDashBoard.SetData()
2020-06-01 08:10:29.8792::DEBUG::UI_AIDE_CommCellServices.AttendanceDashBoard::End : SetData
2020-06-01 08:10:31.1444::DEBUG::UI_AIDE_CommCellServices.AttendanceDashBoard::End : Constructor

**Comment by charissasylim** [comment]
Happening still in 3.3.5. Pops up 4 time then AIDE crashes.

**Comment by charissasylim** [comment]
fixed 3.3.6
